module.exports = {
  inputFiles: ['./src'],
  exclude: '**/*.test.ts',
  mode: 'file',
  theme: 'markdown',
  includeDeclarations: true,
  includeVersion: true,
  tsconfig: 'tsconfig.json',
  out: './dorks',
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  stripInternal: true,
  readme: 'main.md',
  name: 'large-number',
  ignoreCompilerErrors: true,
  hideGenerator: true,
  plugin: 'typedoc-plugin-markdown',
  listInvalidSymbolLinks: true,
};
